/*
Load System Scripts.scd
2/5/2015
*/

//"Submixer EQ Page.scd".loadRelative;
//"Submixer Looper Page.scd".loadRelative;

"APC40 Main Page.scd".loadRelative;
"Base Main Page.scd".loadRelative;

"Effects Page.scd".loadRelative;
"Base Effects Page.scd".loadRelative;

//"Send Page.scd".loadRelative;

//"Base Submixer EQ Page.scd".loadRelative;
//"Base Submixer Looper Page.scd".loadRelative;


s.meter