/*
Load System Scripts.scd
2/5/2015
*/

//"Submixer EQ Page.scd".loadRelative;
//"Submixer Looper Page.scd".loadRelative;

try { "APC40 Main Page.scd".loadRelative; };
try { "Base Main Page.scd".loadRelative; };

try { "Effects Page.scd".loadRelative; };
try { "Base Effects Page.scd".loadRelative; };

//"Send Page.scd".loadRelative;

//"Base Submixer EQ Page.scd".loadRelative;
//"Base Submixer Looper Page.scd".loadRelative;
